spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      # discovery.locator теперь не нужен
      routes:
        # Авторизация пользователя (jwt/auth)
        - id: authentication-service-auth
          uri: http://authentication-service:8081
          predicates:
            - Path=/api/v${app.version}/auth/**
          filters:
            - StripPrefix=2
          metadata:
            auth-required: false

        # Управление пользователями
        - id: authentication-service-users
          uri: http://authentication-service:8081
          predicates:
            - Path=/api/v${app.version}/users/**
          filters:
            - StripPrefix=2

        # 1) Начало OAuth2-Authorization Code Flow
        - id: oauth2-authorization
          uri: http://authentication-service:8081
          predicates:
            - Path=/oauth2/authorization/**
          filters:
            - RewritePath=/oauth2/authorization/(?<seg>.*), /oauth2/authorization/${seg}
          metadata:
            auth-required: false

        # 2) Callback от Google
        - id: oauth2-callback
          uri: http://authentication-service:8081
          predicates:
            - Path=/login/oauth2/code/**
          filters:
            - RewritePath=/login/oauth2/code/(?<seg>.*), /login/oauth2/code/${seg}
          metadata:
            auth-required: false

        # Админка
        - id: authentication-service-admin
          uri: http://authentication-service:8081
          predicates:
            - Path=/api/v${app.version}/admin/**
          filters:
            - StripPrefix=2
          metadata:
            required-role: ADMIN

        # Swagger (документация)
        - id: authentication-service-docs
          uri: http://authentication-service:8081
          predicates:
            - Path=/authentication-service/v3/api-docs/**
          filters:
            - StripPrefix=1
          metadata:
            auth-required: false
          order: -1

        - id: authentication-service-docs-swagger
          uri: http://authentication-service:8081
          predicates:
            - Path=/authentication-service/swagger-ui.html
          filters:
            - StripPrefix=1
          metadata:
            auth-required: false
          order: -1

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
              - Accept
              - X-Requested-With
              - User-Name
              - User-Role
              - Cookie
            exposed-headers:
              - Authorization
              - User-Name
              - User-Role
              - Set-Cookie
            allow-credentials: true
            max-age: 3600

server:
  port: 8080

jwt:
  public-key-path: ${PUBLIC_KEY}
  access:
    expiration: 900000
  refresh:
    expiration: 604800000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    ru.zeker: DEBUG

app:
  version: 1

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs
      - name: authentication-service
        url: /authentication-service/v3/api-docs