spring:
  application:
    name: sandbox-service
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka:9092}
    admin:
      properties:
        offsets.topic.replication-factor: 1
        transactions.state.log.replication-factor: 1
        transactions.state.log.min.isr: 1

feign:
  client:
    config:
      judge0:
        connectTimeout: 2000
        readTimeout: 10000

logging:
  level:
    root: INFO
    ru.zeker: DEBUG

judge0:
  url: ${JUDGE0_URL:https://judge0-ce.p.rapidapi.com}

server:
  port: 8085
